version: '3.8'

services:
  backend:
    build:
      context: https://github.com/avantikasistemas/backend_gestion_proyectos.git#master
      dockerfile: Dockerfile
    container_name: gestion-proyectos-backend
    ports:
      - "8014:8014"
    environment:
      - DRIVER=${DRIVER}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - ENCRYPT=${ENCRYPT}
      - TRUST_CERTIFICATE=${TRUST_CERTIFICATE}
      - MY_SECRET_KEY=${MY_SECRET_KEY}
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: https://github.com/avantikasistemas/frontend_gestion_proyectos.git#master
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://130.1.1.7:8014
    container_name: gestion-proyectos-frontend
    ports:
      - "5189:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
