version: '3.8'

services:
  backend:
    build:
      context: https://github.com/avantikasistemas/backend_contador_dian.git#master
      dockerfile: Dockerfile
    container_name: contador-dian-backend
    ports:
      - "8012:8012"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DRIVER=${DRIVER}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - ENCRYPT=${ENCRYPT}
      - TRUST_CERTIFICATE=${TRUST_CERTIFICATE}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_EMAIL_SENDER=${SMTP_EMAIL_SENDER}
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: https://github.com/avantikasistemas/frontend_contador_dian.git#master
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://130.1.1.7:8012
    container_name: contador-dian-frontend
    ports:
      - "5187:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
